import { Character, RadarStat } from './types';

export const defaultRadarStats: RadarStat[] = [
  { name: '武力', value: 60 },
  { name: '智力', value: 60 },
  { name: '體力', value: 60 },
  { name: '敏捷', value: 60 },
  { name: '魅力', value: 60 },
  { name: '幸運', value: 60 }
];

export const defaultCharacter: Omit<Character, 'id'> = {
  name: '',
  tags: '',
  race: '',
  gender: '',
  age: '',
  height: '',
  weight: '',
  orientation: '',
  spouse: '',
  themeColor: '#06b6d4',
  hairColor: '',
  eyeColor: '',
  backstory: '',
  temperature: '',
  strength: '',
  dominantHand: '右撇子',
  eyesight: '',
  healthStatus: '',
  physicalNotes: '',
  personality: '',
  mbti: '',
  likes: '',
  dislikes: '',
  strengths: '',
  habits: '',
  catchphrase: '',
  imageUrl: '',
  isImported: false,
  isNPC: false,
  radarStats: defaultRadarStats
};

export const defaultNPCs: Character[] = [
  { 
    id: 'npc_yshtola', 
    name: '雅·修朵拉', 
    race: '貓魅族', 
    tags: '拂曉血盟', 
    gender: '女', 
    age: '外表約23歲 (實際秘而不宣)', 
    height: '148cm', 
    weight: '45kg', 
    orientation: '', 
    spouse: '', 
    themeColor: '#d8b4e2', 
    hairColor: '白色', 
    eyeColor: '無神(眼盲)', 
    backstory: '賢人，拂曉血盟的核心成員之一，擅長破壞魔法和古代歷史學物理學。', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '心眼(看不見實體，但能感知魔力乙太)', 
    healthStatus: '健康但長年魔力消耗極大', 
    physicalNotes: '', 
    personality: '沉著冷靜，毒舌且帶有慈母般的嚴厲。', 
    mbti: 'INTJ', 
    likes: '看書、茶、研究乙太', 
    dislikes: '粗魯的人、打擾她讀書的人', 
    strengths: '強大的魔法、淵博的知識', 
    habits: '說教時雙手抱胸', 
    catchphrase: '「既然你想知道，我就好好地教導你吧。」', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: [
      { name: '武力', value: 85 },
      { name: '智力', value: 95 },
      { name: '體力', value: 70 },
      { name: '敏捷', value: 75 },
      { name: '魅力', value: 90 },
      { name: '幸運', value: 80 }
    ]
  },
  { 
    id: 'npc_graha', 
    name: '古·拉哈·提亞', 
    race: '貓魅族', 
    tags: '水晶公', 
    gender: '男', 
    age: '約24歲 (但當了水晶公經歷了100年以上)', 
    height: '162cm', 
    weight: '55kg', 
    orientation: '', 
    spouse: '', 
    themeColor: '#ef4444', 
    hairColor: '紅色', 
    eyeColor: '異色瞳/皇血之紅', 
    backstory: '諾亞調查團的一員，後在第一世界作為水晶公守護水晶塔，並引導光之戰士拯救世界。', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '良好', 
    healthStatus: '部分軀體水晶化(回歸原初世界後恢復)', 
    physicalNotes: '', 
    personality: '熱血、純真、崇拜冒險，非常體貼與忠誠。', 
    mbti: 'ENFP', 
    likes: '與光之戰士一起冒險、三明治', 
    dislikes: '無能為力、珍視的人受傷', 
    strengths: '古老的智慧、水晶塔的防衛機制、魔法', 
    habits: '害羞時抓尾巴或拉兜帽', 
    catchphrase: '「請帶我一起走吧，去到群星彼端冒險！」', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: [
      { name: '武力', value: 80 },
      { name: '智力', value: 90 },
      { name: '體力', value: 85 },
      { name: '敏捷', value: 85 },
      { name: '魅力', value: 95 },
      { name: '幸運', value: 85 }
    ]
  },
  { 
    id: 'npc_alphinaud', 
    name: '阿爾菲諾', 
    race: '精靈族', 
    tags: '拂曉血盟', 
    gender: '男', 
    age: '16歲', 
    height: '155cm', 
    weight: '43kg', 
    orientation: '', 
    spouse: '', 
    themeColor: '#3b82f6', 
    hairColor: '銀色', 
    eyeColor: '藍色', 
    backstory: '拂曉血盟的一員，路易索瓦大師的孫子，原擅長召喚術、現轉為賢者。有著優秀的政治和外交才能，但常有不通世俗的一面。', 
    temperature: '', 
    strength: '', 
    dominantHand: '右手', 
    eyesight: '良好', 
    healthStatus: '健康', 
    physicalNotes: '精緻的五官，與妹妹阿莉塞非常像', 
    personality: '溫柔體貼，富有正義感，早熟但有時容易受打擊，重視友情。', 
    mbti: 'ENFJ', 
    likes: '畫畫、讀書、宏偉的理想', 
    dislikes: '不會游泳、柴米油鹽的價格、嘲笑其身高的人', 
    strengths: '政治談判、素描、賢者魔法', 
    habits: '思考時手抵著下巴', 
    catchphrase: '「拂曉將再次迎接黎明。」', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: [
      { name: '武力', value: 75 },
      { name: '智力', value: 92 },
      { name: '體力', value: 72 },
      { name: '敏捷', value: 78 },
      { name: '魅力', value: 90 },
      { name: '幸運', value: 82 }
    ]
  },
  { 
    id: 'npc_alisaie', 
    name: '阿莉塞', 
    race: '精靈族', 
    tags: '拂曉血盟', 
    gender: '女', 
    age: '16歲', 
    height: '155cm', 
    weight: '42kg', 
    orientation: '', 
    spouse: '', 
    themeColor: '#ec4899', 
    hairColor: '銀色', 
    eyeColor: '藍色', 
    backstory: '阿爾菲諾的雙胞胎妹妹，性格鮮明且行事果決，在經歷許多冒險後成長為令人信賴的赤魔法師。', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '優良', 
    healthStatus: '良好', 
    physicalNotes: '耳上有個與阿爾菲諾對應的耳飾', 
    personality: '熱烈、率直、行動派，不喜歡拐彎抹角，極其護短。', 
    mbti: 'ESFP', 
    likes: '實戰格鬥、游泳、跟哥哥抬槓、甜食', 
    dislikes: '政治遊戲、被人當成小女孩對待、束手無策的無力感', 
    strengths: '赤魔法物理雙修、絕佳的戰鬥本能', 
    habits: '生氣時會跺腳或雙手叉腰', 
    catchphrase: '「不管對手是誰，我都不會退縮半分！」', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: [
      { name: '武力', value: 88 },
      { name: '智力', value: 80 },
      { name: '體力', value: 78 },
      { name: '敏捷', value: 86 },
      { name: '魅力', value: 88 },
      { name: '幸運', value: 80 }
    ]
  },
  { 
    id: 'npc_urianger', 
    name: '尤里安傑', 
    race: '精靈族', 
    tags: '拂曉血盟', 
    gender: '男', 
    age: '29歲', 
    height: '210cm', 
    weight: '78kg', 
    orientation: '', 
    spouse: '', 
    themeColor: '#a855f7', 
    hairColor: '金金色', 
    eyeColor: '琥珀色', 
    backstory: '拂曉血盟的預言研究學家，長年致力於神學和古籍預言的研究，對穆恩布達之死一直抱有愧疚。', 
    temperature: '', 
    strength: '', 
    dominantHand: '左撇子', 
    eyesight: '中度近視(平時戴護目鏡隔絕光線)', 
    healthStatus: '正常(因長年不怎麼走動而缺乏充足體力)', 
    physicalNotes: '身材高大但偏瘦，說話習慣用古雅典口吻', 
    personality: '沉穩、神祕、悲觀主義，但會在背後默默為盟友承擔一切重負。', 
    mbti: 'INFP', 
    likes: '看占星盤、沙拉、在圖書館研究隱祕古文', 
    dislikes: '坐船(嚴重暈船)、炎熱暴曬的戶外、把心事告訴他人', 
    strengths: '星占魔法、預言解讀、卡牌輔助', 
    habits: '用手指扶眼鏡或拿書擋住臉部下半', 
    catchphrase: '「命運編織之線，終將把我們引向應许之地。」', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: [
      { name: '武力', value: 70 },
      { name: '智力', value: 96 },
      { name: '體力', value: 65 },
      { name: '敏捷', value: 72 },
      { name: '魅力', value: 82 },
      { name: '幸運', value: 78 }
    ]
  },
  { 
    id: 'npc_thancred', 
    name: '桑克瑞德', 
    race: '人族', 
    tags: '拂曉血盟', 
    gender: '男', 
    age: '32歲', 
    height: '178cm', 
    weight: '72kg', 
    orientation: '', 
    spouse: '', 
    themeColor: '#78716c', 
    hairColor: '淺灰白色', 
    eyeColor: '一隻眼因乙太紊亂而變成深色(平时戴眼罩遮掩)', 
    backstory: '精通偵察與隱秘行動的特工兼護衛。曾經歷了痛失敏菲利亞的苦痛，在第一世界擔任琳的導師和監護人，並轉職為絕槍戰士。', 
    temperature: '', 
    strength: '', 
    dominantHand: '雙手並用', 
    eyesight: '右眼乙太流失嚴重，只能靠左眼和感知判斷', 
    healthStatus: '乙太流喪失，無法靠自己凝聚魔法，需借用魔法子彈', 
    physicalNotes: '英俊、富有成熟男子韻味，身上帶有少數刀傷', 
    personality: '表面輕浮調侃，內心極其溫柔克制，責任感沉重得令人心疼。', 
    mbti: 'ISTP', 
    likes: '琳的笑容、果實酒、精細手工、甜麵包', 
    dislikes: '無能為力的遺憾、話多的自大狂、無法守護重要之人', 
    strengths: '絕槍防護術、潛入偵察、雙劍格鬥', 
    habits: '不自覺拉扯一下自己的皮手套', 
    catchphrase: '「這一次，我會徹底守護到底！」', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: [
      { name: '武力', value: 90 },
      { name: '智力', value: 82 },
      { name: '體力', value: 88 },
      { name: '敏捷', value: 92 },
      { name: '魅力', value: 94 },
      { name: '幸運', value: 70 }
    ]
  },
  { 
    id: 'npc_estinien', 
    name: '艾斯蒂尼安', 
    race: '精靈族', 
    tags: '蒼天之龍騎士', 
    gender: '男', 
    age: '32歲', 
    height: '210cm', 
    weight: '85kg', 
    orientation: '', 
    spouse: '', 
    themeColor: '#0ea5e9', 
    hairColor: '銀白色', 
    eyeColor: '青藍色', 
    backstory: '伊修加德前「蒼天之龍騎士」，長年扛起與邪龍尼德霍格血戰的宿命。曾被怨念吞噬，但被光之戰士拯救。現作為自由之身守護世界。', 
    temperature: '', 
    strength: '驚人', 
    dominantHand: '右撇子', 
    eyesight: '像蒼鷹一樣銳利', 
    healthStatus: '極其強壯，體內沾染並留存了部分邪龍之血，耐力驚人', 
    physicalNotes: '常年不修邊幅，頭髮微亂，散發著野性魅力', 
    personality: '孤傲、寡言、極度務實、嫌麻煩。雖然冷酷，但重情重義。對金錢概念极其匱乏。', 
    mbti: 'ISTJ', 
    likes: '烤烏賊、美酒、擦拭槍尖、冥想、風乾肉片', 
    dislikes: '繁文縟節、政客、沒有意義的閒聊、被奸商欺騙', 
    strengths: '穿天突刺、邪龍魔力跳躍、狂暴物理打擊', 
    habits: '酷愛坐在屋頂上或高處俯瞰世界', 
    catchphrase: '「...哼，隨你的便。如果需要長槍，隨時叫我。」', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: [
      { name: '武力', value: 96 },
      { name: '智力', value: 75 },
      { name: '體力', value: 95 },
      { name: '敏捷', value: 92 },
      { name: '魅力', value: 88 },
      { name: '幸運', value: 75 }
    ]
  }
];

export const getRadarPoint = (angle: number, value: number, radius: number, centerX: number, centerY: number) => {
  const radian = (angle - 90) * (Math.PI / 180);
  const r = (value / 100) * radius;
  return { x: centerX + r * Math.cos(radian), y: centerY + r * Math.sin(radian) };
};

export const getPointerPos = (e: any) => {
  if (e.touches && e.touches.length > 0) {
    return { x: e.touches[0].clientX, y: e.touches[0].clientY };
  }
  return { x: e.clientX, y: e.clientY };
};
export const questions: string[] = [
  "如果你的角色在路上撿到 10 萬金幣，他會立刻去買什麼？", 
  "描述一次你的角色徹底失控、失去理智的經歷。", 
  "你的角色最害怕死亡的哪一種方式？為什麼？", 
  "如果可以回到過去，你的角色會想改變哪一個決定？", 
  "你的角色在喝醉後會有什麼表現？會吐真言嗎？", 
  "當面對必須犧牲少數來拯救多數的電車難題時，他會怎麼選？", 
  "你的角色有什麼連最親近的人都不知道的「小怪癖」？",
  "在面臨絕對無法戰勝的強敵時，你的角色會選擇逃跑還是戰死？",
  "如果最好的朋友突然背叛了你的角色，他的第一反應會是什麼？",
  "為了達成他一生的最終目標，你的角色願意犧牲什麼代價？",
  "你的角色最拿手的一道料理是什麼？如果讓他下廚會發生什麼事？",
  "如果突然失去了所有戰鬥能力或魔法，你的角色會怎麼度過餘生？",
  "你的角色對於『愛』的定義是什麼？他是一個容易墜入愛河的人嗎？",
  "在萬籟俱寂的夜晚，你的角色最常回想起哪一段回憶？",
  "你的角色對什麼樣的天氣或季節情有終鍾？背後有什麼原因嗎？",
  "如果能和逝去的人說最後一句話，他會對誰說？又會說些什麼？",
  "當被陌生人無端挑釁或侮辱時，你的角色通常會如何反擊？",
  "你的角色要花多長的時間，以及經歷什麼事，才會真正信任一個人？",
  "促使你的角色每天早上醒來、繼續面對這個世界的最主要動力是什麼？",
  "你的角色隨身攜帶、最珍視的物品是什麼？它有著什麼樣的故事？",
  "如果有機會向神明提出一個必定會被解答的問題，他會問什麼？",
  "描述你的角色心目中「最完美的一天」會是如何度過的。"
];
