import { Character, RadarStat } from './types';

export const defaultRadarStats: RadarStat[] = [
  { name: '武力', value: 60 },
  { name: '智力', value: 60 },
  { name: '體力', value: 60 },
  { name: '敏捷', value: 60 },
  { name: '魅力', value: 60 },
  { name: '幸運', value: 60 }
];

export const defaultCharacter: Omit<Character, 'id'> = {
  name: '',
  tags: '',
  race: '',
  gender: '',
  age: '',
  height: '',
  weight: '',
  orientation: '',
  spouse: '',
  themeColor: '#06b6d4',
  hairColor: '',
  eyeColor: '',
  backstory: '',
  temperature: '',
  strength: '',
  dominantHand: '右撇子',
  eyesight: '',
  healthStatus: '',
  physicalNotes: '',
  personality: '',
  mbti: '',
  likes: '',
  dislikes: '',
  strengths: '',
  habits: '',
  catchphrase: '',
  imageUrl: '',
  isImported: false,
  isNPC: false,
  radarStats: defaultRadarStats
};

export const defaultNPCs: Character[] = [
  { 
    id: 'npc_yshtola', 
    name: '雅·修朵拉', 
    race: '', 
    tags: '拂曉血盟', 
    gender: '', 
    age: '', 
    height: '', 
    weight: '', 
    orientation: '', 
    spouse: '', 
    themeColor: '#d8b4e2', 
    hairColor: '', 
    eyeColor: '', 
    backstory: '', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '', 
    healthStatus: '', 
    physicalNotes: '', 
    personality: '', 
    mbti: '', 
    likes: '', 
    dislikes: '', 
    strengths: '', 
    habits: '', 
    catchphrase: '', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: defaultRadarStats
  },
  { 
    id: 'npc_graha', 
    name: '古·拉哈·提亞', 
    race: '', 
    tags: '薩雷安賢人', 
    gender: '', 
    age: '', 
    height: '', 
    weight: '', 
    orientation: '', 
    spouse: '', 
    themeColor: '#ef4444', 
    hairColor: '', 
    eyeColor: '', 
    backstory: '', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '', 
    healthStatus: '', 
    physicalNotes: '', 
    personality: '', 
    mbti: '', 
    likes: '', 
    dislikes: '', 
    strengths: '', 
    habits: '', 
    catchphrase: '', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: defaultRadarStats
  },
  { 
    id: 'npc_alphinaud', 
    name: '阿爾菲諾', 
    race: '', 
    tags: '拂曉血盟', 
    gender: '', 
    age: '', 
    height: '', 
    weight: '', 
    orientation: '', 
    spouse: '', 
    themeColor: '#3b82f6', 
    hairColor: '', 
    eyeColor: '', 
    backstory: '', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '', 
    healthStatus: '', 
    physicalNotes: '', 
    personality: '', 
    mbti: '', 
    likes: '', 
    dislikes: '', 
    strengths: '', 
    habits: '', 
    catchphrase: '', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: defaultRadarStats
  },
  { 
    id: 'npc_alisaie', 
    name: '阿莉塞', 
    race: '', 
    tags: '拂曉血盟', 
    gender: '', 
    age: '', 
    height: '', 
    weight: '', 
    orientation: '', 
    spouse: '', 
    themeColor: '#ec4899', 
    hairColor: '', 
    eyeColor: '', 
    backstory: '', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '', 
    healthStatus: '', 
    physicalNotes: '', 
    personality: '', 
    mbti: '', 
    likes: '', 
    dislikes: '', 
    strengths: '', 
    habits: '', 
    catchphrase: '', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: defaultRadarStats
  },
  { 
    id: 'npc_urianger', 
    name: '尤里安傑', 
    race: '', 
    tags: '拂曉血盟', 
    gender: '', 
    age: '', 
    height: '', 
    weight: '', 
    orientation: '', 
    spouse: '', 
    themeColor: '#a855f7', 
    hairColor: '', 
    eyeColor: '', 
    backstory: '', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '', 
    healthStatus: '', 
    physicalNotes: '', 
    personality: '', 
    mbti: '', 
    likes: '', 
    dislikes: '', 
    strengths: '', 
    habits: '', 
    catchphrase: '', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: defaultRadarStats
  },
  { 
    id: 'npc_thancred', 
    name: '桑克瑞德', 
    race: '', 
    tags: '拂曉血盟', 
    gender: '', 
    age: '', 
    height: '', 
    weight: '', 
    orientation: '', 
    spouse: '', 
    themeColor: '#78716c', 
    hairColor: '', 
    eyeColor: '', 
    backstory: '', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '', 
    healthStatus: '', 
    physicalNotes: '', 
    personality: '', 
    mbti: '', 
    likes: '', 
    dislikes: '', 
    strengths: '', 
    habits: '', 
    catchphrase: '', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: defaultRadarStats
  },
  { 
    id: 'npc_estinien', 
    name: '艾斯蒂尼安', 
    race: '', 
    tags: '蒼天之龍騎士', 
    gender: '', 
    age: '', 
    height: '', 
    weight: '', 
    orientation: '', 
    spouse: '', 
    themeColor: '#0ea5e9', 
    hairColor: '', 
    eyeColor: '', 
    backstory: '', 
    temperature: '', 
    strength: '', 
    dominantHand: '右撇子', 
    eyesight: '', 
    healthStatus: '', 
    physicalNotes: '', 
    personality: '', 
    mbti: '', 
    likes: '', 
    dislikes: '', 
    strengths: '', 
    habits: '', 
    catchphrase: '', 
    imageUrl: '', 
    isNPC: true, 
    radarStats: defaultRadarStats
  }
];

export const getRadarPoint = (angle: number, value: number, radius: number, centerX: number, centerY: number) => {
  const radian = (angle - 90) * (Math.PI / 180);
  const r = (value / 100) * radius;
  return { x: centerX + r * Math.cos(radian), y: centerY + r * Math.sin(radian) };
};

export const getPointerPos = (e: any) => {
  if (e.touches && e.touches.length > 0) {
    return { x: e.touches[0].clientX, y: e.touches[0].clientY };
  }
  return { x: e.clientX, y: e.clientY };
};
export const questions: string[] = [
  "如果你的角色在路上撿到 10 萬金幣，他會立刻去買什麼？", 
  "描述一次你的角色徹底失控、失去理智的經歷。", 
  "你的角色最害怕死亡的哪一種方式？為什麼？", 
  "如果可以回到過去，你的角色會想改變哪一個決定？", 
  "你的角色在喝醉後會有什麼表現？會吐真言嗎？", 
  "當面對必須犧牲少數來拯救多數的電車難題時，他會怎麼選？", 
  "你的角色有什麼連最親近的人都不知道的「小怪癖」？",
  "在面臨絕對無法戰勝的強敵時，你的角色會選擇逃跑還是戰死？",
  "如果最好的朋友突然背叛了你的角色，他的第一反應會是什麼？",
  "為了達成他一生的最終目標，你的角色願意犧牲什麼代價？",
  "你的角色最拿手的一道料理是什麼？如果讓他下廚會發生什麼事？",
  "如果突然失去了所有戰鬥能力或魔法，你的角色會怎麼度過餘生？",
  "你的角色對於『愛』的定義是什麼？他是一個容易墜入愛河的人嗎？",
  "在萬籟俱寂的夜晚，你的角色最常回想起哪一段回憶？",
  "你的角色對什麼樣的天氣或季節情有終鍾？背後有什麼原因嗎？",
  "如果能和逝去的人說最後一句話，他會對誰說？又會說些什麼？",
  "當被陌生人無端挑釁或侮辱時，你的角色通常會如何反擊？",
  "你的角色要花多長的時間，以及經歷什麼事，才會真正信任一個人？",
  "促使你的角色每天早上醒來、繼續面對這個世界的最主要動力是什麼？",
  "你的角色隨身攜帶、最珍視的物品是什麼？它有著什麼樣的故事？",
  "如果有機會向神明提出一個必定會被解答的問題，他會問什麼？",
  "描述你的角色心目中「最完美的一天」會是如何度過的。"
];
